import { GetServerSideProps } from 'next'
import Head from 'next/head';
import React from 'react'
import TodoFormComponent from '../../components/todoForm.component';
import { ITodo } from '../../interfaces/todo.interface'
import axios from '../../lib/axios.config';

const Todo = (props: { data: ITodo }) => {
  return (
    <>
      <Head>
        <title>Edit todo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TodoFormComponent data={props.data} />
    </>
  )
}

export default Todo

export const getServerSideProps: GetServerSideProps<{ data: ITodo }> = async (context) => {
  const id = context.query.id;
  const res = await axios.get<ITodo>('todo/' + id);
  const data = res.data;
  return {
    props: { data },
  }
}